Patch 2
tasuren/niconico.py pull request #12
Opened 2022-03-19 11:20 UTC by tuna2134

まじで途中やり
まあtasurenがやってくれることを信じるわ

2022-03-19 11:25 UTC, tasuren requested changes
`__`にしないで欲しい。

2022-03-19 11:47 UTC, tuna2134 commented
えー

2022-03-19 11:48 UTC, tuna2134 commented
なぜ？

2022-03-19 12:04 UTC, tuna2134 commented
@tasuren 修正完了

2022-03-19 12:57 UTC, tasuren requested changes
propertyじゃなくて`_`じゃなくて直にして欲しい。

2022-03-19 13:18 UTC, tuna2134 commented
なぜ？

2022-03-19 13:18 UTC, tuna2134 commented
> propertyじゃなくて`_`じゃなくて直にして欲しい。

普通にそうした方がいいと思う
なぜなら誰かさんがミスる可能性もあるし、sanicもやっているから。。。

2022-03-19 13:19 UTC, tuna2134 commented
@tasuren

2022-03-19 21:29 UTC, tasuren commented
> > propertyじゃなくて`_`じゃなくて直にして欲しい。
> 
> 普通にpropertyにした方がいいと思う
> なぜなら誰かさんがミスる可能性もあるし、sanicもやっているから。。。

これの場合いじられたくないわけじゃない
Videoとか

2022-03-19 23:28 UTC, tuna2134 commented
ふーん

2022-03-19 23:30 UTC, tuna2134 commented
ふーん
ならそうしとく

2022-03-22 23:11 UTC, tasuren commented
@tuna2134 ブランチを`new`にして欲しい。
次のバージョンの作りかけに含める。

2022-03-28 14:59 UTC, tuna2134 commented
Ok

2022-03-28 21:10 UTC, tasuren approved these changes
Okay

2022-03-28 21:10 UTC, merged