#19 の機能を追加
tasuren/niconico.py pull request #28
Opened 2022-06-10 10:56 UTC by Negima1072

#19 の機能を追加しました。

## 変更点
- `common.py`を作成、Userクラス・CommonClientクラスを実装
- NicoNicoクラスにCommonClientクラスを実装
- Userクラスにいくつかの関数を実装

2022-06-10 11:43 UTC, tasuren requested changes
Wave 1

2022-06-10 11:43 UTC, tasuren commented on niconico/common.py
> +    def get_movies(
```python
    def get_movies(
         self, num: Optional[int] = 100, page: Optional[int] = 1,
         sortKey: Optional[str] = VideoSortKey.registeredAt,
         sortOrder: Optional[str] = "desc"
    ) -> Iterator[AbcVideo]:
```
のように改行と空白入れをして欲しいです。

2022-06-10 11:43 UTC, tasuren commented on niconico/common.py
> +        r = self.client.niconico.request(
変数を作らないで直で`.json()`を付けてreturnして欲しいです。
`return self.client.niconico.request(...).json()`

2022-06-10 11:56 UTC, Negima1072 commented
修正しました。確認をお願いします。

2022-06-10 20:51 UTC, tasuren commented on niconico/common.py
> +    def get_movies(
インデントを一つ分下げて欲しいです。

2022-06-10 20:52 UTC, tasuren requested changes
Wave 2

2022-06-11 06:30 UTC, Negima1072 commented on niconico/common.py
> +    def get_movies(
```python
        ).json()

        for mr in r["data"]["mylists"]:
            yield AbcMyList(mr, self)
    
    def get_movies(
        self, num: Optional[int] = 100, page: Optional[int] = 1,
        sortKey: Optional[str] = VideoSortKey.registeredAt,
        sortOrder: Optional[str] = "desc"
    ) -> Iterator[AbcVideo]:
        """ユーザーのマイリストを取得します。

        Parameters
        ----------
        num : int, default 100"""
```
こんなかんじで大丈夫ですか？

2022-09-16 15:09 UTC, closed without merging